### ISSUE TITLE
Als een webshopmanager wil ik het percentage verkochte pizza’s per categorie    kunnen zien, zodat ik kan bepalen welke categorieën het meest succesvol zijn.

### ISSUE THREAD

**Issue by milanOffermans** [milanOffermans/PizzaDashboard#12]

**Comment by DevKevin88** [comment]
=== Definition of Done ====
    
Percentage Verkochte Pizza’s per Categorie: 

Het dashboard moet een visualisatie tonen die het percentage verkochte pizza’s per categorie weergeeft.
